export const DATA_ATTEMPT = 'DATA_ATTEMPT';
export const REGISTERATION = 'REGISTERATION';
export const SUCCESS = 'SUCCESS';
export const FAIL = 'FAIL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const LOGOUT = 'LOGOUT';
export const FETCH_DATA_ATTEMPT = 'FETCH_DATA_ATTEMPT';
export const FETCH_PARCELS = 'FETCH_PARCELS';
export const FETCH_MORE_PARCELS = 'FETCH_MORE_PARCELS';
export const FETCH_TAKEN_PARCEL = 'FETCH_TAKEN_PARCEL';
export const FETCH_MORE_TAKEN_PARCELS = 'FETCH_MORE_TAKEN_PARCELS';
export const CREATE_PARCEL = 'CREATE_PARCEL';
export const PARCEL_READY = 'PARCEL_READY';
export const PARCEL_DONE = 'PARCEL_DONE';
export const CHOSE_PARCEL = 'CHOSE_PARCEL';
export const CREATE_REPORT = 'CREATE_REPORT'; 
export const CREATE_REPORT_ATTEMPT = 'CREATE_REPORT_ATTEMPT'; 
 